"""empty message

Revision ID: 1558191ba83f
Revises: 
Create Date: 2023-04-27 19:20:26.724740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1558191ba83f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishing_location', schema=None) as batch_op:
        batch_op.alter_column('user_token',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishing_location', schema=None) as batch_op:
        batch_op.alter_column('user_token',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
